Changes workflow dispatch to call and adds outputs

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -3,7 +3,7 @@
 name: Test fake_cpp_project
 
 on:
-  workflow_dispatch:
+  workflow_call:
     inputs:
       gitBranch:
         description: 'The git branch to test'
@@ -13,6 +13,10 @@ on:
       container_id:
         description: "The github run ID from build.yaml"
         required: true
+    outputs:
+      success:
+        description: "Returns if the Tests succeeded."
+        value: ${{ jobs.test.outputs.test_result }}
 
 env:
   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
@@ -21,20 +25,27 @@ env:
 
 jobs:
   test:
+    name: Run Project Tests
     runs-on: [self-hosted, MacOS, ARM64]
+
+    outputs:
+      test_result: ${{ steps.test.test_result }}
 
     steps:
     - uses: actions/checkout@v4
 
-    - name: Check System Requirements
+    - id: check-system-requirements
+      name: Check System Requirements
       run: |
         echo "gitBranch: ${{ inputs.gitBranch }}"
 
-    - name: Setup
+    - id: setup
+      name: Setup
       run: |
         docker run --name test_fake_cpp_project-container-${{ github.run_id }} --detach -i -t -v .:/project-tests alpine /bin/sh
 
-    - name: Configure
+    - id: configure
+      name: Configure
       run: |
         docker exec -w /project-tests test_fake_cpp_project-container-${{ github.run_id }} sh -c "apk update && apk add \
           clang \
@@ -47,20 +58,31 @@ jobs:
           git \
           zlib-dev"
 
-    - name: Generate
+    - id: generate
+      name: Generate
       run: |
         docker exec -w /project-tests test_fake_cpp_project-container-${{ github.run_id }} sh -c "cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G ${{ env.GENERATOR }}"
 
-    - name: Build
+    - id: build
+      name: Build
       run: |
         docker exec -w /project-tests test_fake_cpp_project-container-${{ github.run_id }} sh -c "cmake --build build --config ${{env.BUILD_TYPE}}"
     
-    - name: Test
+    - id: test
+      name: Test
       run: |
         set -e
         docker exec -w /project-tests test_fake_cpp_project-container-${{ github.run_id }} sh -c "ctest --test-dir build --output-on-failure"
+        if [ $? -eq 0 ]; then
+          echo "Tests succeeded."
+          echo "test_result=true" >> $GITHUB_OUTPUT
+        else
+          echo "Tests Failed."
+          echo "test_result=false" >> $GITHUB_OUTPUT
+        fi
 
-    - name: Teardown
+    - id: teardown
+      name: Teardown
       if: always()
       run: |
         echo "Cleaning up container ..."
